---
resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.1.2
    uri: "https://github.com/sasa-stankovic/concourse-tutors.git"
    branch: master
    file: semantic_version_file_placeholder
    private_key:  
    username: sasa-stankovic
    password:  
    git_user: stankovic@sasha.in.rs
    depth:
    commit_message: 

jobs:
- name: bump-version
  public: true
  serial: true
  plan:
  - get: version
    params: {pre: rc}
  - put: version
    params: {file: version/number}
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: version
      run:
        path: cat
        args: [version/number]
